packages:
  - packages/*
catalog:
  gunshi: ^0.23.1
  tsdown: ^0.11.0
  '@pnpm/logger': '>=5.1.0 =<1001.0.0'
  '@pnpm/constants': ^1001.1.0
  '@pnpm/find-workspace-dir': ^1000.1.0
  '@pnpm/workspace.find-packages': ^1000.0.23
  '@pnpm/workspace.read-manifest': ^1000.1.4
