packages:
  - packages/*
catalog:
  gunshi: 0.27.0-beta.6
  '@gunshi/plugin-i18n': 0.27.0-beta.6
  '@gunshi/plugin-renderer': 0.27.0-beta.6
  tsdown: ^0.17.0
  '@pnpm/constants': ^1001.3.1
  '@pnpm/find-workspace-dir': ^1000.1.3
  '@pnpm/workspace.read-manifest': ^1000.2.4
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@kazupon/eslint-config'
  - knip
  - eslint
  - '@types/node'
  - gunshi
  - '@gunshi/plugin-i18n'
  - '@gunshi/plugin'
  - '@gunshi/plugin-renderer'
  - tsdown
  - rolldown
  - '@rolldown/pluginutils'
  - pnpmc
  - pnpmc-show
  - pnpmc-register
  - pnpmc-workspace-find-packages
