packages:
  - packages/*
catalog:
  gunshi: ^0.26.3
  tsdown: ^0.15.0
  '@pnpm/constants': ^1001.3.1
  '@pnpm/find-workspace-dir': ^1000.1.3
  '@pnpm/workspace.read-manifest': ^1000.2.4
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@typescript/native-preview'
  - '@kazupon/eslint-config'
  - knip
  - eslint
  - '@types/node'
