name: nightly release
on:
  push:
    branches:
      - '**'
    tags:
      - '!**'
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # TODO: workaround, see https://github.com/nodejs/corepack/issues/612
      - name: Enable corepack
        run: |
          npm install -g corepack@latest
          corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Release with pkg-pr-new
        run: pnpx pkg-pr-new publish
